"""initial hosted schema

Revision ID: f34f4c65517f
Revises:
Create Date: 2026-09-17 14:06:01.241689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f34f4c65517f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_app_users_active'), 'app_users', ['active'], unique=False)
    op.create_index(op.f('ix_app_users_role'), 'app_users', ['role'], unique=False)
    op.create_table('audit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_audit_history_order_id'), 'audit_history', ['order_id'], unique=False)
    op.create_table('inventory',
    sa.Column('sku', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=False),
    sa.Column('added_stock', sa.Integer(), nullable=False),
    sa.Column('physical_count', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('phone_original', sa.String(length=64), nullable=False),
    sa.Column('phone_normalized', sa.String(length=11), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location_url', sa.Text(), nullable=False),
    sa.Column('order_type', sa.String(length=64), nullable=False),
    sa.Column('honey_qty', sa.Integer(), nullable=False),
    sa.Column('date_qty', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('amount_collected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('courier', sa.String(length=200), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('tracking_number', sa.String(length=200), nullable=False),
    sa.Column('delivery_result', sa.String(length=200), nullable=False),
    sa.Column('feedback_consent', sa.String(length=64), nullable=False),
    sa.Column('feedback_request_date', sa.Date(), nullable=True),
    sa.Column('feedback_status', sa.String(length=64), nullable=False),
    sa.Column('customer_rating', sa.Integer(), nullable=True),
    sa.Column('buy_again', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('returned_sellable', sa.Boolean(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('honey_unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date_unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_phone_normalized'), 'orders', ['phone_normalized'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('synced_revision', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('response_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('taste_rating', sa.Integer(), nullable=True),
    sa.Column('portion_rating', sa.Integer(), nullable=True),
    sa.Column('preparation_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('buy_again', sa.String(length=32), nullable=False),
    sa.Column('recommendation_score', sa.Integer(), nullable=True),
    sa.Column('preferred_flavor', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('issue_reported', sa.Boolean(), nullable=False),
    sa.Column('followup_owner', sa.String(length=200), nullable=False),
    sa.Column('followup_status', sa.String(length=64), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_feedback_order_id'), 'feedback', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_order_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('sync_state')
    op.drop_table('settings')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_phone_normalized'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_audit_history_order_id'), table_name='audit_history')
    op.drop_table('audit_history')
    op.drop_index(op.f('ix_app_users_role'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_active'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
